name: Generate Data and Update Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 执行，可根据需要调整

jobs:
  generate_data:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为运行环境

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # 将仓库代码检出到运行环境

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'  # 使用 Python 3.x 版本

      - name: Install Dependencies (Optional)
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 安装你的 Python 脚本需要的依赖
          pip install base64
          pip install json
          pip install pyaes
          pip install binascii
          pip install datetime

      - name: Execute Python Script
        run: python pyss.py  # 替换成你的 Python 脚本

      - name: Commit and Push Changes
        run: |
          git config --global user.email "1942590224@qq.com"  # 替换成你的机器人邮箱
          git config --global user.name "wangyh"           # 替换成你的机器人名称
          git add ss.txt # 替换成你的生成的文件
          git commit -m "Automated ss data update" || echo "No changes to commit"
          git push origin main  # 替换成你的分支名，如果不是 main
