name: PYSS

on:
  schedule:
    - cron: '2 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          
      - name: 开始
        run: |
          pip3 install requests pyaes
          python3 pyss.py
      - name: 提交文件
        run: |
          git config --global user.email "1942590224@qq.com"
          git config --global user.name "wangyh"
          git add ss
          commit_message="Automated ss data update ($(date +'%Y-%m-%d %H:%M:%S UTC'))"
          git commit -m "$commit_message" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
